version: '3.8'

services:
  # Frontend Angular avec Nginx
  frontend:
    build:
      context: ./starterKit-front
      dockerfile: Dockerfile
    container_name: speedpresta-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - speedpresta-network
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  # Backend NestJS
  backend:
    build:
      context: ./starterKit-back
      dockerfile: Dockerfile
    container_name: speedpresta-backend
    restart: unless-stopped
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgredb.speedpresta.com
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=admin4wfw
      - DB_NAME=wfwdb
      - PORT=3009
    depends_on:
      - postgres
    networks:
      - speedpresta-network

  # Base de données PostgreSQL
  postgres:
    image: postgres:15
    container_name: speedpresta_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wfwdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin4wfw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - speedpresta-network

  # Interface d'administration PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: speedpresta-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - speedpresta-network

volumes:
  postgres_data:

networks:
  speedpresta-network:
    driver: bridge
