version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-lifecycle-backend
    restart: unless-stopped
    ports:
      - "80:3009"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgredb.speedpresta.com
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=admin4wfw
      - DB_NAME=wfwdb
      - PORT=3009
    networks:
      - speedpresta-network

networks:
  speedpresta-network:
    driver: bridge
