version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-lifecycle-backend
    restart: unless-stopped
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=project_lifecycle
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - project-lifecycle-network

  postgres:
    image: postgres:15
    container_name: project-lifecycle-postgres
    restart: always
    environment:
      POSTGRES_DB: project_lifecycle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-lifecycle-network

  #pgadmin:
  #  image: dpage/pgadmin4:latest
  #  container_name: project-lifecycle-pgadmin
  #  restart: always
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@example.com
  #    PGADMIN_DEFAULT_PASSWORD: admin
  #  ports:
  #    - "5050:80"
  #  depends_on:
  #    - postgres
  #  networks:
  #    - project-lifecycle-network

volumes:
  postgres_data:

networks:
  project-lifecycle-network:
    driver: bridge