version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: project-lifecycle-postgres
    restart: always
    environment:
      POSTGRES_DB: project_lifecycle
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-lifecycle-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: project-lifecycle-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - project-lifecycle-network

volumes:
  postgres_data:

networks:
  project-lifecycle-network:
    driver: bridge