version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-kanban-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - frontend-network
    environment:
      - NODE_ENV=production

networks:
  frontend-network:
    driver: bridge 